import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/common/libs/cn";

import { fontHeading } from "@/common/styles/fonts";

import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("font-sans", fontSans.variable, fontHeading.variable)}>{children}</body>
    </html>
  );
}
